config/routes.rb
PsBattles::Application.routes.draw do
  resources :users
  resources :sessions,     only:[:create]
  
  resources :battles do
    resources :posts, controller: "battles/posts"
  end
  
  resources :posts, controller: "battles/posts"  
  
  get "signup"      => "users#new", as: "signup"
  get "signin"      => "sessions#new", as: "signin"
  delete "signout"  => "sessions#destroy", as: "signout"
  
  root 'battles#index'

end

app/models/battle.rb
class Battle < ActiveRecord::Base
  has_many :posts
  has_attached_file :image, 
    styles: { :medium => "400x400>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/battles/posts_controller.rb
class Battles::PostsController < ApplicationController
  before_action :authorize_user!, except:[:index, :show]
  before_action :set_battle, only: [:index, :new, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.scoped
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @battle.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @battle.posts.new( post_params )
    @post.creator = current_user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @battle, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(params[:post])
        format.html { redirect_to @battle, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to battle_url(@battle) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      @battle = @post.battle
    end

    def set_battle
      @battle = Battle.find(params[:battle_id])
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image)
    end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :authorize_user!, except:[:index, :show]
  before_action :set_battle, only: [:show, :edit, :update, :destroy]

  # GET /battles
  # GET /battles.json
  def index
    @battles = Battle.all
  end

  # GET /battles/1
  # GET /battles/1.json
  def show
    
  end

  # GET /battles/new
  def new
    @battle = Battle.new
  end

  # GET /battles/1/edit
  def edit
  end

  # POST /battles
  # POST /battles.json
  def create
    @battle = Battle.new(battle_params)

    respond_to do |format|
      if @battle.save
        @battle = Battle.new(:name => params[:battle][:name], :creator => current_user.email, :created_at => Time.now)
        format.html { redirect_to @battle, notice: 'Battle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @battle }
      else
        format.html { render action: 'new' }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /battles/1
  # PATCH/PUT /battles/1.json
  def update
    respond_to do |format|
      if @battle.update(battle_params)
        format.html { redirect_to @battle, notice: 'Battle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battles/1
  # DELETE /battles/1.json
  def destroy
    @battle.destroy
    respond_to do |format|
      format.html { redirect_to battles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_battle
      @battle = Battle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def battle_params
      params.require(:battle).permit(:name, :description, :creator, :image)
    end
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/battles/_form.html.erb
<%= form_for(@battle) do |f| %>
  <% if @battle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
      <% @battle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
    <% @battle.creator = current_user %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/battles/edit.html.erb
<h1>Editing battle</h1>

<%= render 'form' %>

<%= link_to 'Show', @battle %> |
<%= link_to 'Back', battles_path %>

app/views/battles/index.html.erb
<h1>Listing battles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Creator</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @battles.each do |battle| %>
      <tr>
        <td><%= link_to h(battle.name), battle_path(battle.id) %></td>
        <td><%= battle.description %></td>
        <td><%= battle.creator %></td>
        <td><%= link_to 'Edit', edit_battle_path(battle) %></td>
        <td><%= link_to 'Delete', battle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Battle', new_battle_path %>

app/views/battles/new.html.erb
<h1>New battle</h1>

<%= render 'form' %>

<%= link_to 'Back', battles_path %>

app/views/battles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @battle.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @battle.description %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @battle.creator %>
  
</p>
<p>
  <%= image_tag @battle.image.url(:medium) %>
</p>

<table>
  <tr>
    <th>Replies</th>
  </tr>
  <% @battle.posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= image_tag post.image.url(:thumb) %></td>
      <td><%= link_to "Remove", post_path(post), data: {:confirm => 'Are you sure?'}, :method => :delete %></td>

    </tr>
  <% end %>
</table>

<%= link_to 'Add to the battle', new_battle_post_path(@battle) %>
<%= link_to 'Edit', edit_battle_path(@battle) %> |
<%= link_to 'Back', battles_path %>